services:
  abeonasec-ui:
    container_name: abeonasec-ui
    build: # Build container using aboenasec-ui.Dockerfile
      context: .
      dockerfile: abeonasec-ui.Dockerfile
    ports:
    - "8081:80" # serve on http://{Host IP}:8081 for testing (80 for prod)
    networks:
    - external # using external name for containers bound to Host
    - internal # using internal name for Pod

  # modified example from https://ikarthiks.medium.com/setting-up-elasticsearch-and-kibana-single-node-with-docker-compose-329776fa3aee
  # note that we are setting up certificates regardless of the fact that this service is internal to the Pod network
  # elasticsearch is much happier when run with certs
  elastic-init:
    container_name: elastic-init
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.3.0
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    user: root # required for generating and setting ownership of certs with following shell script
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: abeonasec-es01\n"\
          "    dns:\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        find . -type d -exec chmod 750 \{\} \;;
        find . -type f -exec chmod 640 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -Iv https://host.containers.internal:9200 2>&1 | grep "SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / RSASSA-PSS"; do sleep 10; done;
        echo "All done, exiting...";
        kill -s SIGTERM 1;
      '
    networks:
    - internal
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/abeonasec-es01/abeonasec-es01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  abeonasec-es01: # single node elasticsearch cluster
    container_name: abeonasec-es01
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.3.0
    volumes:
    - data:/usr/share/elasticsearch/data
    - certs:/usr/share/elasticsearch/config/certs
    ports:
      - "9200:9200" # default elasticsearch port
    networks:
    - internal # internal to Pod
    environment:
    - node.name=abeonasec-es01
    - discovery.type=single-node
    - cluster.name=abeonasec-es-cluster
    - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    - bootstrap.memory_lock=true
    - xpack.security.enabled=true
    - xpack.security.http.ssl.enabled=true
    - xpack.security.http.ssl.key=certs/abeonasec-es01/abeonasec-es01.key
    - xpack.security.http.ssl.certificate=certs/abeonasec-es01/abeonasec-es01.crt
    - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
    - xpack.security.transport.ssl.enabled=true
    - xpack.security.transport.ssl.key=certs/abeonasec-es01/abeonasec-es01.key
    - xpack.security.transport.ssl.certificate=certs/abeonasec-es01/abeonasec-es01.crt
    - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
    - xpack.security.transport.ssl.verification_mode=certificate
    # the following are environment variables needed to enable elasticvue 
    # to access the cluster and can be removed later
    - http.cors.enabled=true
    - http.cors.allow-origin=/.*/
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  # elasticvue for development purposes
  DEV-abeonasec-elasticvue:
    container_name: DEV-abeonasec-elasticvue
    image: docker.io/cars10/elasticvue:latest
    ports:
      - "8080:8080" # exposed to host for viewing
    environment:
    - ELASTICVUE_CLUSTERS='[{"name":"abeonasec-es-cluster", "uri":"https://localhost:9200", "username":"elastic", "password":"$ELASTIC_PASSWORD"}]'
    networks:
    - external
    depends_on:
    - abeonasec-es01

volumes:
  ui:
    driver: local
  data:
    driver: local
  certs:
    driver: local

networks:
  internal: {}
  external: {}